# Generated by Django 4.1 on 2022-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemeet', '0003_meeting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='ending_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starting_date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
