# Generated by Django 4.1 on 2022-08-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemeet', '0004_alter_meeting_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='ending_date_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='starting_date_time',
        ),
    ]
